// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    CarbonCampsite: typeof import('~icons/carbon/campsite')['default']
    CarbonDicomOverlay: typeof import('~icons/carbon/dicom-overlay')['default']
    CarbonLanguage: typeof import('~icons/carbon/language')['default']
    CarbonLogoGithub: typeof import('~icons/carbon/logo-github')['default']
    CarbonMoon: typeof import('~icons/carbon/moon')['default']
    CarbonSun: typeof import('~icons/carbon/sun')['default']
    CartItem: typeof import('./src/cart/components/CartItem.vue')['default']
    Footer: typeof import('./src/common/components/Footer.vue')['default']
    ProductItem: typeof import('./src/products/components/ProductItem.vue')['default']
    README: typeof import('./src/common/components/README.md')['default']
    VButton: typeof import('./src/common/components/VButton.vue')['default']
    VButtonText: typeof import('./src/common/components/VButtonText.vue')['default']
    VDescription: typeof import('./src/common/components/VDescription.vue')['default']
    VInput: typeof import('./src/common/components/VInput.vue')['default']
    VTitleLg: typeof import('./src/common/components/VTitleLg.vue')['default']
  }
}

export { }
